### ISSUE TITLE
Crashes in VS 2017 axml designer?

### ISSUE THREAD

**Issue by MagnusJohansson** [Cheesebaron/SlidingUpPanel#12]
Is this just me?

Adding the SlidingUpPanel causes the axml designer to crash:
(Attached the .axml)

```
Setting id 1 on newly created ClassLoader

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.v7.widget.AppCompatImageView

Trying to load class android.support.v7.widget.AppCompatImageView

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.v4.widget.DrawerLayout

Trying to load class md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout

Trying to load class android.support.design.widget.CoordinatorLayout

Trying to load class android.support.design.widget.AppBarLayout

Trying to load class android.support.v7.widget.Toolbar

Trying to load class android.support.constraint.ConstraintLayout

An exception occured while loading control android.support.constraint.ConstraintLayout
java.lang.NoClassDefFoundError: android/support/constraint/solver/widgets/ConstraintWidget
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at mono.android.SessionProjectCallback.instantiateClass(SessionProjectCallback.java:336)
	at mono.android.SessionProjectCallback.loadView(SessionProjectCallback.java:178)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:157)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:854)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:197)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:854)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at mono.android.DesignerSession.load(DesignerSession.java:222)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:693)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: android.support.constraint.solver.widgets.ConstraintWidget
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at mono.android.LibraryClassLoader.findClass(LibraryClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more

Trying to load class android.support.v4.widget.NestedScrollView

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.v7.widget.AppCompatButton

Trying to load class android.support.v7.widget.AppCompatButton

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.design.widget.NavigationView

Trying to load class android.support.design.internal.NavigationMenuView

Trying to load class com.android.layoutlib.bridge.android.support.Adapter

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.design.internal.NavigationMenuItemView

Trying to load class android.support.v7.widget.AppCompatCheckedTextView

Trying to load class android.support.design.internal.NavigationMenuItemView

Trying to load class android.support.v7.widget.AppCompatCheckedTextView

Trying to load class android.support.design.internal.NavigationMenuItemView

Trying to load class android.support.v7.widget.AppCompatCheckedTextView

Trying to load class android.support.v7.widget.AppCompatTextView

Trying to load class android.support.design.internal.NavigationMenuItemView

Trying to load class android.support.v7.widget.AppCompatCheckedTextView

Trying to load class android.support.design.internal.NavigationMenuItemView

Trying to load class android.support.v7.widget.AppCompatCheckedTextView

mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
	at mono.android.DesignerException.fromThrowable(DesignerException.java:43)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:177)
	at mono.android.DesignerSession.load(DesignerSession.java:228)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:693)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Cheesebaron.SlidingUpPanel.SlidingUpPanelLayout.ComputeScroll () [0x00000] in C:\projects\slidinguppanel\src\SlidingUpPanel\SlidingUpPanelLayout.cs:647 
  at Android.Views.View.n_ComputeScroll (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <ce9491aaa0be4c32aaa9b777d81ba291>:0 
  at (wrapper dynamic-method) System.Object:9b00cbef-82cf-420d-b4bc-714c71a597d0 (intptr,intptr)
	at md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout.n_computeScroll(Native Method)
	at md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout.computeScroll(SlidingUpPanelLayout.java:141)
	at android.view.View.draw(View.java:16847)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:505)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:434)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at mono.android.DesignerSession.load(DesignerSession.java:222)
	... 4 more


```

[mainactivity.zip](https://github.com/Cheesebaron/SlidingUpPanel/files/974218/mainactivity.zip)

**Comment by Cheesebaron** [comment]
The error indicates that the `_dragHelper` has not been created:

https://github.com/Cheesebaron/SlidingUpPanel/blob/master/src/SlidingUpPanel/SlidingUpPanelLayout.cs#L647

Not sure if another constructor is needed, but it could look like the one where `_dragHelper` is instantiated is not called.

**Comment by KNSSoftware** [comment]
Phew, it is not just me, but I am getting something slightly different!  For me, it is happening in VS2015.

To clarify, it crashes the designer, but compiles/runs fine.  

Thanks.

```
Creating LibraryClassLoader in shadow copy path C:\Users\John\AppData\Local\Temp\AndroidDesignerJars199846259571487357
Setting id 1 on newly created ClassLoader

Trying to load class md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout

android.view.InflateException: Binary XML file line #129: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:163)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at mono.android.DesignerSession.load(DesignerSession.java:233)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:702)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.content.res.Resources$NotFoundException: Item 1 in entries (resource id 0x3e9) is not a valid array resource.
	at android.content.res.BridgeTypedArray.getTextArray(BridgeTypedArray.java:724)
	at android.widget.AbsSpinner.<init>(AbsSpinner.java:76)
	at android.widget.Spinner.<init>(Spinner.java:240)
	at android.widget.Spinner.<init>(Spinner.java:207)
	at android.widget.Spinner.<init>(Spinner.java:157)
	at android.widget.Spinner.<init>(Spinner.java:141)
	... 40 more

Bridge [broken] Binary XML file line #129: Error inflating class <unknown>
android.view.InflateException: Binary XML file line #333: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:163)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at mono.android.DesignerSession.load(DesignerSession.java:233)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:702)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.content.res.Resources$NotFoundException: Item 1 in entries (resource id 0x3e9) is not a valid array resource.
	at android.content.res.BridgeTypedArray.getTextArray(BridgeTypedArray.java:724)
	at android.widget.AbsSpinner.<init>(AbsSpinner.java:76)
	at android.widget.Spinner.<init>(Spinner.java:240)
	at android.widget.Spinner.<init>(Spinner.java:207)
	at android.widget.Spinner.<init>(Spinner.java:157)
	at android.widget.Spinner.<init>(Spinner.java:141)
	... 40 more

Bridge [broken] Binary XML file line #333: Error inflating class <unknown>
android.view.InflateException: Binary XML file line #360: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:163)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at mono.android.DesignerSession.load(DesignerSession.java:233)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:702)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.content.res.Resources$NotFoundException: Item 1 in entries (resource id 0x3e9) is not a valid array resource.
	at android.content.res.BridgeTypedArray.getTextArray(BridgeTypedArray.java:724)
	at android.widget.AbsSpinner.<init>(AbsSpinner.java:76)
	at android.widget.Spinner.<init>(Spinner.java:240)
	at android.widget.Spinner.<init>(Spinner.java:207)
	at android.widget.Spinner.<init>(Spinner.java:157)
	at android.widget.Spinner.<init>(Spinner.java:141)
	... 40 more

Bridge [broken] Binary XML file line #360: Error inflating class <unknown>
Trying to load class fragment

Trying to load class md5e87191de366c7e0322091708f85a5c67.SatelliteMenuButton

Trying to load class md5e87191de366c7e0322091708f85a5c67.SatelliteMenuButton

mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
	at mono.android.DesignerException.fromThrowable(DesignerException.java:46)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:187)
	at mono.android.DesignerSession.load(DesignerSession.java:239)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:702)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:745)
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Cheesebaron.SlidingUpPanel.SlidingUpPanelLayout.ComputeScroll () [0x00000] in C:\projects\slidinguppanel\src\SlidingUpPanel\SlidingUpPanelLayout.cs:647 
  at Android.Views.View.n_ComputeScroll (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <61dabd3f0b0446bc8b570d6071d995d7>:0 
  at (wrapper dynamic-method) System.Object:57964c6f-dd74-439a-b0e3-ea5f3bd8630d (intptr,intptr)
	at md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout.n_computeScroll(Native Method)
	at md546c45d491b042b167774b8aaeb1a2ac0.SlidingUpPanelLayout.computeScroll(SlidingUpPanelLayout.java:141)
	at android.view.View.draw(View.java:16850)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16977)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17074)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:401)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:548)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:422)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:434)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at mono.android.DesignerSession.load(DesignerSession.java:233)
	... 4 more

```

**Comment by greg2fs** [comment]
I have the same issue, my project compiles and run fine but I can't open the designer:

`Creating LibraryClassLoader in shadow copy path C:\Users\Greg\AppData\Local\Temp\AndroidDesignerJars4292655400707090533
Setting id 1 on newly created ClassLoader

Trying to load class md5bde103fb2d0b82977bb7171c7129eb6b.Dessin

mono.android.DesignerException: System.NullReferenceException: Object reference not set to an instance of an object
	at mono.android.DesignerException.fromThrowable(DesignerException.java:46)
	at mono.android.DesignerSession.checkRenderResultForError(DesignerSession.java:187)
	at mono.android.DesignerSession.load(DesignerSession.java:239)
	at mono.android.DesignerSession.processMessage(DesignerSession.java:704)
	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at MyProject.Droid.Dessin.OnDraw (Android.Graphics.Canvas canvas) [0x00009] in C:\Users\Greg\source\repos\MyProject\MyProject\MyProject.Android\dessin.cs:70 
  at Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x0000f] in <9663139ab15947a89e15a6bcd9621f68>:0 
  at (wrapper dynamic-method) System.Object:a2d4f363-3edb-4b7f-b725-f32619e72136 (intptr,intptr,intptr)
	at md5bde103fb2d0b82977bb7171c7129eb6b.Dessin.n_onDraw(Native Method)
	at md5bde103fb2d0b82977bb7171c7129eb6b.Dessin.onDraw(Dessin.java:53)
	at android.view.View.draw(View.java:17071)
	at android.view.View.draw(View.java:16979)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16977)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17181)
	at android.widget.ScrollView.draw(ScrollView.java:1722)
	at android.view.View.draw(View.java:16979)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17074)
	at android.view.View.draw(View.java:16979)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16977)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16977)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17074)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:401)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:548)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:422)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:434)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at mono.android.DesignerSession.load(DesignerSession.java:233)
	... 4 more`

**Comment by Cheesebaron** [comment]
Thank you for your reports and sorry for the time it took to fix this. I've pushed some changes that should address these issues. Please try again against version 1.1.0. If the issue still persists, please open a new issue.
